import type { FastifyInstance } from 'fastify';
import { AppError, ERROR_CODES, requestUploadSchema, submitOcrSchema } from '@dawaee/shared';
import { withUser, withUserReadOnly } from '../lib/db.js';
import { loadConfig } from '../config.js';
import { authenticate, currentUser } from '../middleware/context.js';
import { requireProfileAccess } from '../services/access-service.js';
import { ALLOWED_IMAGE_TYPES, buildObjectKey, LocalStorageProvider, sniffImageType, type Providers } from '../providers/index.js';

/**
 * Image upload and OCR.
 *
 * Upload security, in order of application:
 *  1. the declared content type must be an allowed image type,
 *  2. the declared size must be within the cap,
 *  3. the object key is generated by the server — the client's filename is
 *     never used, so a crafted name cannot traverse or collide,
 *  4. on the bytes themselves, the magic-byte sniff must agree with the
 *     declared type, which is what rejects a renamed script or a polyglot,
 *  5. the object lands in a private bucket and is only ever read through a
 *     short-lived signed URL.
 */
export function registerUploadRoutes(app: FastifyInstance, providers: Providers): void {
  const cfg = loadConfig();

  app.addHook('preHandler', async (req) => {
    if (req.url.startsWith('/v1/uploads') && !req.url.startsWith('/v1/uploads/local')) {
      await authenticate(req, null as never);
    }
    if (req.url.startsWith('/v1/ocr')) await authenticate(req, null as never);
  });

  app.post('/v1/uploads/request', async (req) => {
    const body = requestUploadSchema.parse(req.body);
    const { userId } = currentUser(req);

    if (!ALLOWED_IMAGE_TYPES.has(body.contentType)) {
      throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Unsupported image type');
    }
    if (body.byteSize > cfg.UPLOAD_MAX_BYTES) {
      throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, `File exceeds the ${Math.floor(cfg.UPLOAD_MAX_BYTES / 1024 / 1024)} MB limit`);
    }

    return withUser(userId, async (tx) => {
      if (body.patientProfileId) {
        await requireProfileAccess(tx, userId, body.patientProfileId, 'add_medication');
      }
      const objectKey = buildObjectKey(body.purpose, body.patientProfileId ?? null, body.contentType);
      const ticket = await providers.storage.createUploadTicket({
        objectKey, contentType: body.contentType, byteSize: body.byteSize,
      });
      await tx.query(
        `INSERT INTO stored_objects
           (object_key, owner_user_id, patient_profile_id, purpose, content_type, byte_size)
         VALUES ($1,$2,$3,$4,$5,$6)`,
        [objectKey, userId, body.patientProfileId ?? null, body.purpose, body.contentType, body.byteSize],
      );
      return { objectKey, upload: ticket };
    });
  });

  /**
   * Short-lived read URL. Images are never served from a public bucket.
   *
   * P19-1. This route used to rely on row-level security alone, and the comment
   * where the check should have been said so:
   *
   *     // RLS on stored_objects means an object belonging to another patient
   *     // simply is not visible here.
   *
   * True, and not the question. The policy on `stored_objects` is
   *
   *     owner_user_id = app.current_user_id()
   *     OR (patient_profile_id IS NOT NULL AND app.can_read_profile(...))
   *
   * and `app.can_read_profile` is `owns_profile OR caregives_profile` — ANY
   * active caregiver, with no reference to the permission set at all. Measured:
   * a caregiver holding only `view_adherence`, refused 403 on `/v1/medications`
   * and `/v1/today` in the same session, obtained a working read URL for the
   * patient's PRESCRIPTION IMAGE. The signed URL then serves the bytes with no
   * further authorization, so it is a complete disclosure, not a hint.
   *
   * This is the P12 class of defect — an app layer asking for fewer permissions
   * than the data it hands back — on the one route P12 did not cover. A
   * prescription photograph is medication identity in its most direct form, so
   * it requires the same permission the medication list does.
   *
   * `avatar` is deliberately exempt: a profile picture is not medication data,
   * and every caregiver is meant to see whose profile they are looking at.
   *
   * The uploader keeps access to what they uploaded. Medication-image creation
   * now explicitly depends on `view_medications`, so a caregiver who can create
   * the image can also review the medication identity it represents.
   */
  app.get('/v1/uploads/url', async (req) => {
    const { objectKey } = req.query as { objectKey?: string };
    if (!objectKey) throw AppError.badRequest(ERROR_CODES.VALIDATION_FAILED, 'objectKey is required');
    const { userId } = currentUser(req);

    return withUserReadOnly(userId, async (tx) => {
      // RLS still scopes this to objects the caller is related to at all: an
      // unrelated patient's object is invisible and answers 404, exactly as a
      // key that does not exist does.
      const { rows } = await tx.query<{
        object_key: string; patient_profile_id: string | null; owner_user_id: string; purpose: string;
      }>(
        `SELECT object_key, patient_profile_id, owner_user_id, purpose
           FROM stored_objects WHERE object_key = $1`,
        [objectKey],
      );
      const object = rows[0];
      if (!object) throw AppError.notFound('Object not found');

      const carriesMedicationIdentity = object.purpose === 'medication_image'
        || object.purpose === 'prescription_image';
      if (object.patient_profile_id && object.owner_user_id !== userId && carriesMedicationIdentity) {
        // 403 rather than 404: the caller is legitimately in this patient's care
        // circle, and P12 settled that an explicit refusal beats a screen that
        // silently shows nothing.
        await requireProfileAccess(tx, userId, object.patient_profile_id, 'view_medications');
      }

      return { url: await providers.storage.createReadUrl(objectKey, 300), expiresInSeconds: 300 };
    });
  });

  /**
   * Local-disk upload sink for development. Signature-checked and
   * content-sniffed exactly like the production path so the security
   * behaviour under test matches what ships.
   */
  if (providers.storage instanceof LocalStorageProvider) {
    const local = providers.storage;
    app.addContentTypeParser(
      ['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/octet-stream'],
      { parseAs: 'buffer' },
      (_req, body, done) => done(null, body),
    );

    app.put('/v1/uploads/local/:objectKey', async (req, reply) => {
      const { objectKey } = req.params as { objectKey: string };
      const { expires, sig } = req.query as { expires?: string; sig?: string };
      const decoded = decodeURIComponent(objectKey);
      if (!expires || !sig || !local.verifyLocalSignature(decoded, Number(expires), sig, 'put')) {
        throw AppError.forbidden('Invalid or expired upload signature');
      }
      const body = req.body as Buffer;
      if (!Buffer.isBuffer(body) || body.length === 0) {
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Empty upload');
      }
      if (body.length > cfg.UPLOAD_MAX_BYTES) {
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'File too large');
      }
      const sniffed = sniffImageType(body);
      if (!sniffed) throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'File content is not a supported image');

      await local.putObject(decoded, body);
      return reply.status(200).send({ ok: true, contentType: sniffed, bytes: body.length });
    });

    app.get('/v1/uploads/local/:objectKey', async (req, reply) => {
      const { objectKey } = req.params as { objectKey: string };
      const { expires, sig } = req.query as { expires?: string; sig?: string };
      const decoded = decodeURIComponent(objectKey);
      if (!expires || !sig || !local.verifyLocalSignature(decoded, Number(expires), sig, 'get')) {
        throw AppError.forbidden('Invalid or expired read signature');
      }
      const buf = await local.getObject(decoded);
      return reply
        .header('content-type', sniffImageType(buf) ?? 'application/octet-stream')
        .header('cache-control', 'private, max-age=60')
        .header('x-content-type-options', 'nosniff')
        .send(buf);
    });
  }

  /**
   * Run OCR over an uploaded image.
   *
   * Returns a review payload, never a saved record. The response is explicitly
   * labelled as unconfirmed AI output, and no medication or schedule exists
   * until the user posts the confirmed values back through /v1/medications.
   *
   * The object is bound to the same patient profile and to the purpose it was
   * uploaded for. RLS alone is not enough here: one account may legitimately
   * own several patient profiles, so an object visible to that account still
   * must not be relabelled as belonging to a different patient during OCR.
   */
  app.post('/v1/ocr/analyze', {
    config: { rateLimit: { max: 20, timeWindow: '5 minutes' } },
  }, async (req) => {
    const body = submitOcrSchema.parse(req.body);
    const { userId } = currentUser(req);

    const objectMeta = await withUserReadOnly(userId, async (tx) => {
      await requireProfileAccess(tx, userId, body.patientProfileId, 'add_medication');
      const { rows: consent } = await tx.query<{ granted: boolean }>(
        `SELECT granted FROM consents WHERE user_id = $1 AND type = 'ocr_image_processing'`,
        [userId],
      );
      // Sending a photo of a prescription to a third-party vision API is a
      // disclosure; it requires a recorded, revocable consent.
      if (!consent[0]?.granted) {
        throw new AppError(
          ERROR_CODES.CONSENT_REQUIRED, 428,
          'Image analysis requires your consent to process medication images',
        );
      }
      const { rows } = await tx.query<{
        object_key: string; content_type: string; patient_profile_id: string | null; purpose: string;
      }>(
        `SELECT object_key, content_type, patient_profile_id, purpose
           FROM stored_objects WHERE object_key = $1`,
        [body.imageKey],
      );
      const object = rows[0];
      if (!object || object.patient_profile_id !== body.patientProfileId) {
        // Do not let a visible object be rebound to another profile. Returning
        // the same 404 as an unknown key keeps the object/profile relationship
        // from becoming an oracle for callers who do not already know it.
        throw AppError.notFound('Image not found');
      }

      const expectedPurpose = body.kind === 'medication_label' ? 'medication_image' : 'prescription_image';
      if (object.purpose !== expectedPurpose) {
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Image purpose does not match OCR request');
      }
      return object;
    });

    let buffer: Buffer;
    try {
      buffer = await providers.storage.getObject(objectMeta.object_key);
    } catch {
      throw new AppError(ERROR_CODES.PROVIDER_UNAVAILABLE, 503, 'The image could not be read for analysis');
    }

    const sniffed = sniffImageType(buffer);
    if (!sniffed) throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Stored file is not a supported image');

    try {
      if (body.kind === 'medication_label') {
        const result = await providers.ocr.readMedicationLabel(buffer, sniffed);
        return {
          kind: 'medication_label',
          provider: result.provider,
          language: result.language,
          // Everything below is a SUGGESTION. Nothing is saved.
          detected: result.fields,
          rawText: result.rawText,
          requiresUserConfirmation: true,
          disclaimerKey: 'medication.aiDisclaimer',
          provenanceLabelKey: 'medication.detectedByAi',
        };
      }

      const result = await providers.ocr.readPrescription(buffer, sniffed);
      return {
        kind: 'prescription',
        provider: result.provider,
        language: result.language,
        prescriber: result.prescriber ?? null,
        issuedDate: result.issuedDate ?? null,
        lines: result.lines,
        rawText: result.rawText,
        requiresUserConfirmation: true,
        // Stated explicitly in the payload: a prescription scan never creates
        // schedules on its own.
        schedulesCreated: 0,
        disclaimerKey: 'medication.aiDisclaimer',
        provenanceLabelKey: 'medication.detectedByAi',
      };
    } catch (err) {
      req.log.error({ provider: providers.ocr.name, err: (err as Error).message }, 'OCR analysis failed');
      throw new AppError(ERROR_CODES.PROVIDER_UNAVAILABLE, 503, 'Image analysis is temporarily unavailable. You can enter the details manually.');
    }
  });
}
