import type { FastifyInstance } from 'fastify';
import { AppError, ERROR_CODES, requestUploadSchema, submitOcrSchema } from '@dawaee/shared';
import { withUser, withUserReadOnly } from '../lib/db.js';
import { loadConfig } from '../config.js';
import { authenticate, currentUser } from '../middleware/context.js';
import { requireProfileAccess } from '../services/access-service.js';
import { ALLOWED_IMAGE_TYPES, buildObjectKey, LocalStorageProvider, sniffImageType, type Providers } from '../providers/index.js';

/**
 * Image upload and OCR.
 *
 * Upload security, in order of application:
 *  1. the declared content type must be an allowed image type,
 *  2. the declared size must be within the cap,
 *  3. the object key is generated by the server — the client's filename is
 *     never used, so a crafted name cannot traverse or collide,
 *  4. direct S3/R2 uploads are finalized against the actual stored bytes before
 *     any application read is permitted,
 *  5. on the bytes themselves, the magic-byte sniff must agree with the
 *     declared type, which is what rejects a renamed script or a polyglot,
 *  6. the object lands in a private bucket and is only ever read through a
 *     short-lived signed URL.
 */
export function registerUploadRoutes(app: FastifyInstance, providers: Providers): void {
  const cfg = loadConfig();

  app.addHook('preHandler', async (req) => {
    if (req.url.startsWith('/v1/uploads') && !req.url.startsWith('/v1/uploads/local')) {
      await authenticate(req, null as never);
    }
    if (req.url.startsWith('/v1/ocr')) await authenticate(req, null as never);
  });

  app.post('/v1/uploads/request', async (req) => {
    const body = requestUploadSchema.parse(req.body);
    const { userId } = currentUser(req);

    if (!ALLOWED_IMAGE_TYPES.has(body.contentType)) {
      throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Unsupported image type');
    }
    if (body.byteSize > cfg.UPLOAD_MAX_BYTES) {
      throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, `File exceeds the ${Math.floor(cfg.UPLOAD_MAX_BYTES / 1024 / 1024)} MB limit`);
    }

    return withUser(userId, async (tx) => {
      if (body.patientProfileId) {
        await requireProfileAccess(tx, userId, body.patientProfileId, 'add_medication');
      }
      const objectKey = buildObjectKey(body.purpose, body.patientProfileId ?? null, body.contentType);
      const ticket = await providers.storage.createUploadTicket({
        objectKey, contentType: body.contentType, byteSize: body.byteSize,
      });
      await tx.query(
        `INSERT INTO stored_objects
           (object_key, owner_user_id, patient_profile_id, purpose, content_type, byte_size)
         VALUES ($1,$2,$3,$4,$5,$6)`,
        [objectKey, userId, body.patientProfileId ?? null, body.purpose, body.contentType, body.byteSize],
      );
      return { objectKey, upload: ticket };
    });
  });

  /**
   * Complete a direct upload before the object becomes application-visible.
   *
   * The upload lease in stored_objects is authoritative. S3/R2 receives the
   * bytes directly, so neither the browser's Content-Length nor the caller's
   * declared byteSize is trusted. We read through the provider's bounded path,
   * compare the ACTUAL byte count and magic bytes, and only then stamp
   * uploaded_at. A mismatch is logically rejected first, then physically
   * removed; if physical cleanup fails the rejected row remains inaccessible
   * and housekeeping can retry cleanup later.
   *
   * Only the uploader may finalize the lease. This is deliberately stronger
   * than profile RLS because another active caregiver can legitimately see the
   * same patient while having no authority over another user's staged upload.
   */
  app.post('/v1/uploads/finalize', async (req) => {
    const raw = req.body as { objectKey?: unknown } | null;
    const objectKey = typeof raw?.objectKey === 'string' ? raw.objectKey : '';
    if (!objectKey || objectKey.length > 512) {
      throw AppError.badRequest(ERROR_CODES.VALIDATION_FAILED, 'objectKey is required');
    }
    const { userId } = currentUser(req);

    const object = await withUserReadOnly(userId, async (tx) => {
      const { rows } = await tx.query<{
        object_key: string;
        owner_user_id: string | null;
        content_type: string;
        byte_size: number;
        uploaded_at: Date | null;
        scan_status: string;
      }>(
        `SELECT object_key, owner_user_id, content_type, byte_size, uploaded_at, scan_status
           FROM stored_objects WHERE object_key = $1`,
        [objectKey],
      );
      const row = rows[0];
      if (!row || row.owner_user_id !== userId || row.scan_status === 'rejected') {
        throw AppError.notFound('Object not found');
      }
      return row;
    });

    // A successful replay is harmless and must not re-read provider bytes after
    // the lease has already been finalized.
    if (object.uploaded_at) return { ok: true, objectKey };

    let buffer: Buffer;
    try {
      buffer = await providers.storage.getObject(objectKey, object.byte_size);
    } catch (err) {
      const message = err instanceof Error ? err.message : '';
      if (message.includes('exceeds configured upload limit') || message.includes('size does not match declared upload size')) {
        await withUser(userId, async (tx) => {
          await tx.query(
            `UPDATE stored_objects
                SET scan_status = 'rejected', reject_reason = 'actual_size_mismatch'
              WHERE object_key = $1 AND owner_user_id = $2 AND uploaded_at IS NULL`,
            [objectKey, userId],
          );
        });
        try {
          await providers.storage.deleteObject(objectKey);
          await withUser(userId, async (tx) => {
            await tx.query(
              `DELETE FROM stored_objects
                WHERE object_key = $1 AND owner_user_id = $2 AND uploaded_at IS NULL AND scan_status = 'rejected'`,
              [objectKey, userId],
            );
          });
        } catch {
          // The logical rejection is already durable. Do not turn a cleanup
          // failure into a path that can read or OCR the object.
        }
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Uploaded bytes do not match the approved upload lease');
      }
      throw new AppError(ERROR_CODES.PROVIDER_UNAVAILABLE, 503, 'The uploaded image could not be verified');
    }

    const sniffed = sniffImageType(buffer);
    const invalid = buffer.length !== object.byte_size || sniffed !== object.content_type;
    if (invalid) {
      await withUser(userId, async (tx) => {
        await tx.query(
          `UPDATE stored_objects
              SET scan_status = 'rejected',
                  reject_reason = CASE
                    WHEN byte_size <> $3 THEN 'actual_size_mismatch'
                    ELSE 'content_type_mismatch'
                  END
            WHERE object_key = $1 AND owner_user_id = $2 AND uploaded_at IS NULL`,
          [objectKey, userId, buffer.length],
        );
      });
      try {
        await providers.storage.deleteObject(objectKey);
        await withUser(userId, async (tx) => {
          await tx.query(
            `DELETE FROM stored_objects
              WHERE object_key = $1 AND owner_user_id = $2 AND uploaded_at IS NULL AND scan_status = 'rejected'`,
            [objectKey, userId],
          );
        });
      } catch {
        // See above: rejected metadata is the fail-closed state.
      }
      throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Uploaded bytes do not match the approved upload lease');
    }

    const finalized = await withUser(userId, async (tx) => {
      const { rowCount } = await tx.query(
        `UPDATE stored_objects
            SET uploaded_at = now(), scan_status = 'clean', reject_reason = NULL
          WHERE object_key = $1 AND owner_user_id = $2 AND uploaded_at IS NULL AND scan_status <> 'rejected'`,
        [objectKey, userId],
      );
      return (rowCount ?? 0) === 1;
    });
    if (!finalized) {
      // A concurrent retry can reach the provider at the same time as this
      // request. Exactly one compare-and-set UPDATE wins; the loser must not
      // report a false 404 when the same uploader's twin request has already
      // completed the very same lease. Re-read only the owner-scoped terminal
      // state. Missing, rejected, cross-account, and still-pending rows remain
      // failures, and no database lock is held across the provider read.
      const alreadyFinalized = await withUserReadOnly(userId, async (tx) => {
        const { rows } = await tx.query<{ uploaded_at: Date | null; scan_status: string }>(
          `SELECT uploaded_at, scan_status
             FROM stored_objects
            WHERE object_key = $1 AND owner_user_id = $2`,
          [objectKey, userId],
        );
        return Boolean(rows[0]?.uploaded_at && rows[0]?.scan_status === 'clean');
      });
      if (!alreadyFinalized) throw AppError.notFound('Object not found');
    }
    return { ok: true, objectKey };
  });

  /**
   * Short-lived read URL. Images are never served from a public bucket.
   *
   * P19-1. This route used to rely on row-level security alone, and the comment
   * where the check should have been said so:
   *
   *     // RLS on stored_objects means an object belonging to another patient
   *     // simply is not visible here.
   *
   * True, and not the question. The policy on `stored_objects` is
   *
   *     owner_user_id = app.current_user_id()
   *     OR (patient_profile_id IS NOT NULL AND app.can_read_profile(...))
   *
   * and `app.can_read_profile` is `owns_profile OR caregives_profile` — ANY
   * active caregiver, with no reference to the permission set at all. Measured:
   * a caregiver holding only `view_adherence`, refused 403 on `/v1/medications`
   * and `/v1/today` in the same session, obtained a working read URL for the
   * patient's PRESCRIPTION IMAGE. The signed URL then serves the bytes with no
   * further authorization, so it is a complete disclosure, not a hint.
   *
   * This is the P12 class of defect — an app layer asking for fewer permissions
   * than the data it hands back — on the one route P12 did not cover. A
   * prescription photograph is medication identity in its most direct form, so
   * it requires the same permission the medication list does.
   *
   * `avatar` is deliberately exempt: a profile picture is not medication data,
   * and every caregiver is meant to see whose profile they are looking at.
   *
   * The uploader keeps access to what they uploaded. Medication-image creation
   * now explicitly depends on `view_medications`, so a caregiver who can create
   * the image can also review the medication identity it represents.
   *
   * The object key is also private routing metadata. New clients send it in a
   * header so the upstream platform request path does not retain it; legacy
   * query transport remains temporarily accepted during rollout. Conflicting
   * values fail closed rather than letting one layer authorize a different key.
   */
  app.get('/v1/uploads/url', async (req) => {
    const { objectKey: legacyObjectKey } = req.query as { objectKey?: string };
    const rawHeader = req.headers['x-dawaee-object-key'];
    if (Array.isArray(rawHeader)) {
      throw AppError.badRequest(ERROR_CODES.VALIDATION_FAILED, 'Invalid object routing metadata');
    }
    const headerObjectKey = typeof rawHeader === 'string' ? rawHeader.trim() : '';
    if (headerObjectKey.length > 512) {
      throw AppError.badRequest(ERROR_CODES.VALIDATION_FAILED, 'Invalid object routing metadata');
    }
    if (legacyObjectKey && headerObjectKey && legacyObjectKey !== headerObjectKey) {
      throw AppError.badRequest(ERROR_CODES.VALIDATION_FAILED, 'Conflicting object routing metadata');
    }
    const objectKey = headerObjectKey || legacyObjectKey;
    if (!objectKey || objectKey.length > 512) {
      throw AppError.badRequest(ERROR_CODES.VALIDATION_FAILED, 'objectKey is required');
    }
    const { userId } = currentUser(req);

    return withUserReadOnly(userId, async (tx) => {
      // RLS still scopes this to objects the caller is related to at all: an
      // unrelated patient's object is invisible and answers 404, exactly as a
      // key that does not exist does.
      const { rows } = await tx.query<{
        object_key: string; patient_profile_id: string | null; owner_user_id: string | null;
        purpose: string; uploaded_at: Date | null; scan_status: string;
      }>(
        `SELECT object_key, patient_profile_id, owner_user_id, purpose, uploaded_at, scan_status
           FROM stored_objects WHERE object_key = $1`,
        [objectKey],
      );
      const object = rows[0];
      if (!object || !object.uploaded_at || object.scan_status === 'rejected') {
        throw AppError.notFound('Object not found');
      }

      const carriesMedicationIdentity = object.purpose === 'medication_image'
        || object.purpose === 'prescription_image';
      if (object.patient_profile_id && object.owner_user_id !== userId && carriesMedicationIdentity) {
        // 403 rather than 404: the caller is legitimately in this patient's care
        // circle, and P12 settled that an explicit refusal beats a screen that
        // silently shows nothing.
        await requireProfileAccess(tx, userId, object.patient_profile_id, 'view_medications');
      }

      return { url: await providers.storage.createReadUrl(objectKey, 300), expiresInSeconds: 300 };
    });
  });

  /**
   * Local-disk upload sink for development. Signature-checked and
   * content-sniffed exactly like the production path so the security
   * behaviour under test matches what ships.
   */
  if (providers.storage instanceof LocalStorageProvider) {
    const local = providers.storage;
    app.addContentTypeParser(
      ['image/jpeg', 'image/png', 'image/webp', 'image/heic', 'application/octet-stream'],
      { parseAs: 'buffer' },
      (_req, body, done) => done(null, body),
    );

    app.put('/v1/uploads/local/:objectKey', async (req, reply) => {
      const { objectKey } = req.params as { objectKey: string };
      const { expires, sig } = req.query as { expires?: string; sig?: string };
      const decoded = decodeURIComponent(objectKey);
      if (!expires || !sig || !local.verifyLocalSignature(decoded, Number(expires), sig, 'put')) {
        throw AppError.forbidden('Invalid or expired upload signature');
      }
      const body = req.body as Buffer;
      if (!Buffer.isBuffer(body) || body.length === 0) {
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Empty upload');
      }
      if (body.length > cfg.UPLOAD_MAX_BYTES) {
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'File too large');
      }
      const sniffed = sniffImageType(body);
      if (!sniffed) throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'File content is not a supported image');

      await local.putObject(decoded, body);
      return reply.status(200).send({ ok: true, contentType: sniffed, bytes: body.length });
    });

    app.get('/v1/uploads/local/:objectKey', async (req, reply) => {
      const { objectKey } = req.params as { objectKey: string };
      const { expires, sig } = req.query as { expires?: string; sig?: string };
      const decoded = decodeURIComponent(objectKey);
      if (!expires || !sig || !local.verifyLocalSignature(decoded, Number(expires), sig, 'get')) {
        throw AppError.forbidden('Invalid or expired read signature');
      }
      const buf = await local.getObject(decoded);
      return reply
        .header('content-type', sniffImageType(buf) ?? 'application/octet-stream')
        .header('cache-control', 'private, max-age=60')
        .header('x-content-type-options', 'nosniff')
        .send(buf);
    });
  }

  /**
   * Run OCR over an uploaded image.
   *
   * Returns a review payload, never a saved record. The response is explicitly
   * labelled as unconfirmed AI output, and no medication or schedule exists
   * until the user posts the confirmed values back through /v1/medications.
   *
   * The object is bound to the same patient profile and to the purpose it was
   * uploaded for. RLS alone is not enough here: one account may legitimately
   * own several patient profiles, so an object visible to that account still
   * must not be relabelled as belonging to a different patient during OCR.
   */
  app.post('/v1/ocr/analyze', {
    config: { rateLimit: { max: 20, timeWindow: '5 minutes' } },
  }, async (req) => {
    const body = submitOcrSchema.parse(req.body);
    const { userId } = currentUser(req);

    const objectMeta = await withUserReadOnly(userId, async (tx) => {
      await requireProfileAccess(tx, userId, body.patientProfileId, 'add_medication');
      // An explicit decision for this profile, including withdrawal, overrides
      // the account-wide default. Another profile's consent is not applicable.
      const { rows: consent } = await tx.query<{ granted: boolean }>(
        `SELECT granted FROM consents
          WHERE user_id = $1 AND type = 'ocr_image_processing'
            AND (patient_profile_id = $2 OR patient_profile_id IS NULL)
          ORDER BY patient_profile_id NULLS LAST
          LIMIT 1`,
        [userId, body.patientProfileId],
      );
      // Sending a photo of a prescription to a third-party vision API is a
      // disclosure; it requires a recorded, revocable consent.
      if (!consent[0]?.granted) {
        throw new AppError(
          ERROR_CODES.CONSENT_REQUIRED, 428,
          'Image analysis requires your consent to process medication images',
        );
      }
      const { rows } = await tx.query<{
        object_key: string; content_type: string; byte_size: number;
        patient_profile_id: string | null; purpose: string;
        uploaded_at: Date | null; scan_status: string;
      }>(
        `SELECT object_key, content_type, byte_size, patient_profile_id, purpose, uploaded_at, scan_status
           FROM stored_objects WHERE object_key = $1`,
        [body.imageKey],
      );
      const object = rows[0];
      if (!object || object.patient_profile_id !== body.patientProfileId || !object.uploaded_at || object.scan_status === 'rejected') {
        // Do not let a visible or merely staged object be rebound to another
        // profile. Returning the same 404 as an unknown key keeps the
        // object/profile relationship from becoming an oracle.
        throw AppError.notFound('Image not found');
      }

      const expectedPurpose = body.kind === 'medication_label' ? 'medication_image' : 'prescription_image';
      if (object.purpose !== expectedPurpose) {
        throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Image purpose does not match OCR request');
      }
      return object;
    });

    let buffer: Buffer;
    try {
      // The database row is the upload lease the API approved. Direct S3/R2
      // upload means those bytes never passed through Fastify, so a max-size
      // check alone is not enough: require the object OCR reads to match the
      // exact byte count that was approved when the ticket was issued.
      buffer = await providers.storage.getObject(objectMeta.object_key, objectMeta.byte_size);
    } catch {
      throw new AppError(ERROR_CODES.PROVIDER_UNAVAILABLE, 503, 'The image could not be read for analysis');
    }

    const sniffed = sniffImageType(buffer);
    if (!sniffed || sniffed !== objectMeta.content_type) {
      throw AppError.badRequest(ERROR_CODES.UPLOAD_REJECTED, 'Stored file is not the approved image type');
    }

    // Storage reads can cross a revocation instant. Authorization and consent
    // are live disclosure boundaries, not capabilities captured at request
    // start, so read them again after the potentially slow object fetch and
    // immediately before handing the image bytes to the external OCR provider.
    await withUserReadOnly(userId, async (tx) => {
      await requireProfileAccess(tx, userId, body.patientProfileId, 'add_medication');
      const { rows: consent } = await tx.query<{ granted: boolean }>(
        `SELECT granted FROM consents
          WHERE user_id = $1 AND type = 'ocr_image_processing'
            AND (patient_profile_id = $2 OR patient_profile_id IS NULL)
          ORDER BY patient_profile_id NULLS LAST
          LIMIT 1`,
        [userId, body.patientProfileId],
      );
      if (!consent[0]?.granted) {
        throw new AppError(
          ERROR_CODES.CONSENT_REQUIRED, 428,
          'Image analysis requires your consent to process medication images',
        );
      }
    });

    try {
      if (body.kind === 'medication_label') {
        const result = await providers.ocr.readMedicationLabel(buffer, sniffed);
        return {
          kind: 'medication_label',
          provider: result.provider,
          language: result.language,
          // Everything below is a SUGGESTION. Nothing is saved.
          detected: result.fields,
          rawText: result.rawText,
          requiresUserConfirmation: true,
          disclaimerKey: 'medication.aiDisclaimer',
          provenanceLabelKey: 'medication.detectedByAi',
        };
      }

      const result = await providers.ocr.readPrescription(buffer, sniffed);
      return {
        kind: 'prescription',
        provider: result.provider,
        language: result.language,
        prescriber: result.prescriber ?? null,
        issuedDate: result.issuedDate ?? null,
        lines: result.lines,
        rawText: result.rawText,
        requiresUserConfirmation: true,
        // Stated explicitly in the payload: a prescription scan never creates
        // schedules on its own.
        schedulesCreated: 0,
        disclaimerKey: 'medication.aiDisclaimer',
        provenanceLabelKey: 'medication.detectedByAi',
      };
    } catch (err) {
      req.log.error({ provider: providers.ocr.name, err: (err as Error).message }, 'OCR analysis failed');
      throw new AppError(ERROR_CODES.PROVIDER_UNAVAILABLE, 503, 'Image analysis is temporarily unavailable. You can enter the details manually.');
    }
  });
}
