import type {
  AuditAction, CalendarSystem, CaregiverNotifyMode, CaregiverPermission, CaregiverRelationshipStatus,
  CaregiverRole, ConfirmationMethod, ConsentType, DeliveryStatus, DoseEventType, DoseStatus, DoseUnit,
  FoodInstruction, Locale, MeasurementType, MedicationForm, MedicationStatus, NotificationChannel,
  NotificationKind, NumeralSystem, ScheduleRuleKind, StrengthUnit, SymptomTag, TravelPolicy,
} from './enums.js';

export type UUID = string;
/** ISO-8601 instant in UTC, e.g. 2026-09-02T17:00:00.000Z */
export type Instant = string;
/** Calendar date with no time component, e.g. 2026-09-02 */
export type LocalDate = string;
/** Wall-clock time of day, HH:mm (24h) */
export type LocalTime = string;
/** IANA timezone identifier, e.g. Asia/Riyadh */
export type TimeZone = string;

// ---------------------------------------------------------------- accounts

export interface User {
  id: UUID;
  phoneE164: string | null;
  email: string | null;
  displayName: string;
  locale: Locale;
  timezone: TimeZone;
  createdAt: Instant;
  disabledAt: Instant | null;
}

/**
 * A person whose medication is being managed. One account may own several
 * (e.g. the user plus their father and mother). Medical data never crosses
 * profile boundaries.
 */
export interface PatientProfile {
  id: UUID;
  ownerUserId: UUID;
  /** Set when this profile belongs to a user who signed in themselves. */
  linkedUserId: UUID | null;
  displayName: string;
  birthYear: number | null;
  avatarKey: string | null;
  timezone: TimeZone;
  /** Timezone the schedules were authored in; used by travel mode. */
  homeTimezone: TimeZone;
  travelPolicy: TravelPolicy;
  isSelf: boolean;
  createdAt: Instant;
  archivedAt: Instant | null;
}

export interface UserPreferences {
  userId: UUID;
  locale: Locale;
  numeralSystem: NumeralSystem;
  calendarSystem: CalendarSystem;
  elderlyMode: boolean;
  textScale: number;
  highContrast: boolean;
  voiceRemindersEnabled: boolean;
  voiceConfirmationEnabled: boolean;
  appLockEnabled: boolean;
  appLockAreas: string[];
  quietHoursStart: LocalTime | null;
  quietHoursEnd: LocalTime | null;
  defaultSnoozeMinutes: number;
  lowStockThresholdDays: number;
  expiryWarningDays: number;
  updatedAt: Instant;
}

// ------------------------------------------------------------- medications

export interface Medication {
  id: UUID;
  patientProfileId: UUID;
  name: string;
  brandName: string | null;
  genericName: string | null;
  form: MedicationForm;
  strengthValue: number | null;
  strengthUnit: StrengthUnit | null;
  manufacturer: string | null;
  barcode: string | null;
  imageKey: string | null;
  /** Free-text as printed / dictated. Never generated by the system. */
  instructions: string | null;
  doctorInstructions: string | null;
  foodInstruction: FoodInstruction;
  notes: string | null;
  status: MedicationStatus;
  startDate: LocalDate;
  endDate: LocalDate | null;
  expiryDate: LocalDate | null;
  prescriptionId: UUID | null;
  /** Provenance of the identity fields — 'user' or 'ocr_confirmed_by_user'. */
  identitySource: 'user' | 'ocr_confirmed_by_user' | 'barcode_confirmed_by_user';
  createdBy: UUID;
  createdAt: Instant;
  updatedAt: Instant;
  archivedAt: Instant | null;
}

export interface MedicationStock {
  medicationId: UUID;
  /** Quantity is expressed in dose units (tablets, ml, puffs...). */
  unit: DoseUnit;
  initialQuantity: number | null;
  remainingQuantity: number | null;
  /** Patient-set threshold override; falls back to preferences. */
  lowStockThresholdDays: number | null;
  trackingEnabled: boolean;
  lastRefillAt: Instant | null;
  updatedAt: Instant;
}

export interface StockTransaction {
  id: UUID;
  medicationId: UUID;
  /** Negative for consumption, positive for refills/corrections. */
  delta: number;
  reason: 'dose_taken' | 'dose_undone' | 'refill' | 'manual_correction' | 'initial' | 'discard';
  doseOccurrenceId: UUID | null;
  balanceAfter: number | null;
  actorUserId: UUID | null;
  createdAt: Instant;
}

// ---------------------------------------------------------------- schedules

export interface FixedTimesRule {
  kind: 'fixed_times';
  /** Wall-clock times in the schedule timezone. */
  times: LocalTime[];
}

export interface IntervalRule {
  kind: 'interval';
  everyHours: number;
  /** First dose time of the day, wall clock. */
  anchorTime: LocalTime;
  /** Optional window outside of which no dose is generated (sleep protection). */
  activeFrom?: LocalTime;
  activeUntil?: LocalTime;
}

export interface DaysOfWeekRule {
  kind: 'days_of_week';
  /** 0 = Sunday … 6 = Saturday (Saudi week starts Sunday). */
  weekdays: number[];
  times: LocalTime[];
}

export interface CycleRule {
  kind: 'cycle';
  daysOn: number;
  daysOff: number;
  times: LocalTime[];
  /** Day 1 of the first "on" block. */
  cycleAnchorDate: LocalDate;
}

export interface AsNeededRule {
  kind: 'as_needed';
  maxPerDay?: number;
  minHoursBetween?: number;
}

export type ScheduleRule = FixedTimesRule | IntervalRule | DaysOfWeekRule | CycleRule | AsNeededRule;

export interface MedicationSchedule {
  id: UUID;
  medicationId: UUID;
  patientProfileId: UUID;
  rule: ScheduleRule;
  ruleKind: ScheduleRuleKind;
  doseQuantity: number;
  doseUnit: DoseUnit;
  /** Timezone the wall-clock times are interpreted in. */
  timezone: TimeZone;
  startDate: LocalDate;
  endDate: LocalDate | null;
  /** Minutes after the scheduled time before the dose counts as missed. */
  missedAfterMinutes: number;
  /** Minutes after the scheduled time still counted as "taken late". */
  lateAfterMinutes: number;
  active: boolean;
  createdBy: UUID;
  createdAt: Instant;
  updatedAt: Instant;
}

// ------------------------------------------------------------------- doses

export interface DoseOccurrence {
  id: UUID;
  scheduleId: UUID;
  medicationId: UUID;
  patientProfileId: UUID;
  /** The authoritative instant this dose is due. */
  scheduledAt: Instant;
  /** Wall-clock rendering captured at generation time, for display + travel mode. */
  scheduledLocalDate: LocalDate;
  scheduledLocalTime: LocalTime;
  scheduledTimezone: TimeZone;
  doseQuantity: number;
  doseUnit: DoseUnit;
  status: DoseStatus;
  notifiedAt: Instant | null;
  snoozedUntil: Instant | null;
  snoozeCount: number;
  confirmedAt: Instant | null;
  confirmedByUserId: UUID | null;
  confirmationMethod: ConfirmationMethod | null;
  /** Escalation stage index already dispatched (0 = none). */
  escalationStage: number;
  escalationCompletedAt: Instant | null;
  /** Client-supplied idempotency key for offline confirmations. */
  clientEventId: string | null;
  createdAt: Instant;
  updatedAt: Instant;
}

export interface DoseEvent {
  id: UUID;
  doseOccurrenceId: UUID;
  patientProfileId: UUID;
  type: DoseEventType;
  at: Instant;
  actorUserId: UUID | null;
  method: ConfirmationMethod | null;
  deviceId: string | null;
  metadata: Record<string, unknown>;
}

export interface SymptomNote {
  id: UUID;
  patientProfileId: UUID;
  doseOccurrenceId: UUID | null;
  tags: SymptomTag[];
  /** Verbatim patient text. Never interpreted by the system. */
  text: string | null;
  recordedAt: Instant;
  createdBy: UUID;
}

export interface HealthMeasurement {
  id: UUID;
  patientProfileId: UUID;
  type: MeasurementType;
  /** systolic/diastolic for BP; single value otherwise. */
  valuePrimary: number;
  valueSecondary: number | null;
  unit: string;
  measuredAt: Instant;
  doseOccurrenceId: UUID | null;
  note: string | null;
  createdBy: UUID;
}

// -------------------------------------------------------------- caregivers

export interface CaregiverRelationship {
  id: UUID;
  patientProfileId: UUID;
  /** Null until the invitation is accepted. */
  caregiverUserId: UUID | null;
  invitedPhoneE164: string | null;
  invitedName: string | null;
  role: CaregiverRole;
  status: CaregiverRelationshipStatus;
  permissions: CaregiverPermission[];
  /** Lower number = contacted earlier during escalation. */
  escalationPriority: number;
  invitationTokenHash: string | null;
  invitationExpiresAt: Instant | null;
  invitedByUserId: UUID;
  acceptedAt: Instant | null;
  revokedAt: Instant | null;
  createdAt: Instant;
  updatedAt: Instant;
}

export interface CaregiverNotificationRule {
  id: UUID;
  relationshipId: UUID;
  channel: NotificationChannel;
  mode: CaregiverNotifyMode;
  /** For 'consecutive_missed'. */
  consecutiveMissedThreshold: number;
  /** Local time the digest is sent, in the patient's timezone. */
  summaryTime: LocalTime | null;
  quietHoursStart: LocalTime | null;
  quietHoursEnd: LocalTime | null;
  enabled: boolean;
  updatedAt: Instant;
}

// ------------------------------------------------------------- escalation

export interface EscalationStage {
  /** Minutes after the scheduled dose time. */
  afterMinutes: number;
  /** Who to contact at this stage. */
  target: 'patient' | 'primary_caregiver' | 'secondary_caregivers' | 'all_caregivers';
  channels: NotificationChannel[];
}

export interface EscalationPolicy {
  id: UUID;
  patientProfileId: UUID;
  /** Null = applies to every medication on the profile. */
  medicationId: UUID | null;
  enabled: boolean;
  stages: EscalationStage[];
  /** Stop escalating entirely between these local times. */
  quietHoursStart: LocalTime | null;
  quietHoursEnd: LocalTime | null;
  updatedAt: Instant;
}

// ----------------------------------------------------------- notifications

export interface NotificationDelivery {
  id: UUID;
  patientProfileId: UUID;
  recipientUserId: UUID | null;
  recipientPhoneE164: string | null;
  kind: NotificationKind;
  channel: NotificationChannel;
  doseOccurrenceId: UUID | null;
  medicationId: UUID | null;
  status: DeliveryStatus;
  providerMessageId: string | null;
  errorCode: string | null;
  attempts: number;
  /** Idempotency guard — one row per logical notification. */
  dedupeKey: string;
  scheduledFor: Instant;
  sentAt: Instant | null;
  updatedAt: Instant;
}

export interface PushToken {
  id: UUID;
  userId: UUID;
  token: string;
  platform: 'ios' | 'android' | 'web';
  deviceId: string;
  appVersion: string | null;
  active: boolean;
  lastSeenAt: Instant;
  createdAt: Instant;
}

// ---------------------------------------------------------------- refills

export interface RefillEvent {
  id: UUID;
  medicationId: UUID;
  quantityAdded: number;
  unit: DoseUnit;
  pharmacy: string | null;
  cost: number | null;
  note: string | null;
  refilledAt: Instant;
  createdBy: UUID;
}

export interface Prescription {
  id: UUID;
  patientProfileId: UUID;
  reference: string | null;
  prescriberName: string | null;
  facility: string | null;
  issuedDate: LocalDate | null;
  expiryDate: LocalDate | null;
  imageKey: string | null;
  /** Raw OCR payload retained only for user review. */
  ocrRaw: Record<string, unknown> | null;
  ocrStatus: 'none' | 'pending' | 'completed' | 'failed';
  createdBy: UUID;
  createdAt: Instant;
}

// ------------------------------------------------------------- emergency

export interface EmergencyCard {
  id: UUID;
  patientProfileId: UUID;
  patientDisplayName: string;
  bloodType: string | null;
  /** Verbatim user-entered allergy list. Never inferred. */
  allergies: string[];
  conditionsNote: string | null;
  emergencyContacts: Array<{ name: string; phoneE164: string; relation: string | null }>;
  includeMedications: boolean;
  includeAllergies: boolean;
  includeContacts: boolean;
  qrEnabled: boolean;
  qrTokenHash: string | null;
  qrRotatedAt: Instant | null;
  updatedAt: Instant;
}

// ----------------------------------------------------------------- consent

export interface Consent {
  id: UUID;
  userId: UUID;
  patientProfileId: UUID | null;
  type: ConsentType;
  granted: boolean;
  version: string;
  grantedAt: Instant | null;
  withdrawnAt: Instant | null;
  ipHash: string | null;
}

// ------------------------------------------------------------------ audit

export interface AuditLogEntry {
  id: string;
  at: Instant;
  actorUserId: UUID | null;
  actorRole: 'patient' | 'caregiver' | 'system' | 'admin';
  patientProfileId: UUID | null;
  action: AuditAction;
  entityType: string;
  entityId: string | null;
  previousValue: Record<string, unknown> | null;
  newValue: Record<string, unknown> | null;
  requestId: string | null;
  ipHash: string | null;
}

// -------------------------------------------------------------- analytics

export interface AdherenceSummary {
  from: LocalDate;
  to: LocalDate;
  scheduled: number;
  taken: number;
  takenOnTime: number;
  takenLate: number;
  skipped: number;
  missed: number;
  pending: number;
  /** taken / (scheduled - pending), 0–100, rounded to 1dp. Null if nothing resolved. */
  adherencePercent: number | null;
}

export interface StockForecast {
  medicationId: UUID;
  remainingQuantity: number;
  dailyConsumption: number;
  daysRemaining: number | null;
  runoutDate: LocalDate | null;
  isLow: boolean;
  thresholdDays: number;
}
