import type { FastifyError, FastifyInstance, FastifyReply, FastifyRequest } from 'fastify';
import { ZodError } from 'zod';
import { AppError, ERROR_CODES, type ApiErrorBody } from '@dawaee/shared';
import { isPgError, PG_ERRORS } from '../lib/db.js';
import { hasWebBundle, sendWebBundle } from '../routes/web-app.js';

/**
 * One place that decides what the outside world learns about a failure.
 *
 * Two rules: an unexpected error never leaks its message or stack to the
 * client, and a permission failure never reveals whether the resource exists.
 */
export function registerErrorHandler(app: FastifyInstance): void {
  app.setErrorHandler((err: FastifyError | Error, req: FastifyRequest, reply: FastifyReply) => {
    const requestId = req.id;

    if (err instanceof AppError) {
      req.log.info({ code: err.code, statusCode: err.statusCode, requestId }, 'handled application error');
      const body: ApiErrorBody = {
        error: { code: err.code, message: err.message, requestId, ...(err.details ? { details: err.details } : {}) },
      };
      return reply.status(err.statusCode).send({ ...body, ...(err.meta ? { meta: err.meta } : {}) });
    }

    if (err instanceof ZodError) {
      return reply.status(400).send({
        error: {
          code: ERROR_CODES.VALIDATION_FAILED,
          message: 'Request validation failed',
          details: err.issues.map((i) => ({ path: i.path.join('.'), message: i.message })),
          requestId,
        },
      } satisfies ApiErrorBody);
    }

    // Postgres told us "no" — usually RLS. Report it as not-found so the API
    // cannot be used to probe which patient ids exist.
    if (isPgError(err, PG_ERRORS.INSUFFICIENT_PRIVILEGE)) {
      req.log.warn({ requestId }, 'database refused the operation (RLS or grant)');
      return reply.status(404).send({
        error: { code: ERROR_CODES.NOT_FOUND, message: 'Resource not found', requestId },
      } satisfies ApiErrorBody);
    }
    if (isPgError(err, PG_ERRORS.UNIQUE_VIOLATION)) {
      return reply.status(409).send({
        error: { code: ERROR_CODES.CONFLICT, message: 'This record already exists', requestId },
      } satisfies ApiErrorBody);
    }

    // These are genuine malformed caller values. They remain validation errors
    // because the user can actually correct the request.
    if (
      isPgError(err, PG_ERRORS.INVALID_TEXT_REPRESENTATION) ||
      isPgError(err, PG_ERRORS.INVALID_DATETIME_FORMAT) ||
      isPgError(err, PG_ERRORS.INVALID_ROW_COUNT_IN_LIMIT)
    ) {
      return reply.status(400).send({
        error: { code: ERROR_CODES.VALIDATION_FAILED, message: 'One of the supplied values is malformed', requestId },
      } satisfies ApiErrorBody);
    }

    if (isPgError(err, PG_ERRORS.FOREIGN_KEY_VIOLATION)) {
      req.log.warn(
        { requestId, constraint: (err as { constraint?: string }).constraint },
        'request referenced a row that does not exist',
      );
      return reply.status(400).send({
        error: { code: ERROR_CODES.VALIDATION_FAILED, message: 'One of the referenced records does not exist', requestId },
      } satisfies ApiErrorBody);
    }

    if (isPgError(err, PG_ERRORS.CHECK_VIOLATION) || isPgError(err, PG_ERRORS.RAISE_EXCEPTION)) {
      // Keep the client payload free of schema details, but log the safe
      // discriminator fields so a production failure can be diagnosed without
      // blaming the user for an infrastructure or migration defect.
      req.log.warn(
        {
          requestId,
          pgCode: (err as { code?: string }).code,
          constraint: (err as { constraint?: string }).constraint,
        },
        'database data rule rejected the operation',
      );
      return reply.status(400).send({
        error: { code: ERROR_CODES.VALIDATION_FAILED, message: 'The request violates a data rule', requestId },
      } satisfies ApiErrorBody);
    }

    const statusCode = (err as FastifyError).statusCode;

    if (statusCode === 429) {
      req.log.info({ requestId }, 'rate limited');
      return reply.status(429).send({
        error: { code: ERROR_CODES.RATE_LIMITED, message: 'Too many requests. Please slow down.', requestId },
      } satisfies ApiErrorBody);
    }

    // Do not collapse every 4xx generated by Fastify/plugins into
    // VALIDATION_FAILED. Doing so produced misleading UI such as "check the
    // information you entered" for authorization and missing-resource errors.
    if (statusCode && statusCode < 500) {
      const code = statusCode === 401
        ? ERROR_CODES.UNAUTHENTICATED
        : statusCode === 403
          ? ERROR_CODES.FORBIDDEN
          : statusCode === 404
            ? ERROR_CODES.NOT_FOUND
            : statusCode === 409
              ? ERROR_CODES.CONFLICT
              : ERROR_CODES.VALIDATION_FAILED;
      return reply.status(statusCode).send({
        error: { code, message: err.message, requestId },
      } satisfies ApiErrorBody);
    }

    req.log.error({ err, requestId }, 'unhandled error');
    return reply.status(500).send({
      error: { code: ERROR_CODES.INTERNAL, message: 'An unexpected error occurred', requestId },
    } satisfies ApiErrorBody);
  });

  app.setNotFoundHandler((req, reply) => {
    // The web app routes on history paths, so a refresh on /today or a shared
    // link to /medications arrives here. Those must return the app, not a JSON
    // 404 — but only for a browser asking for a document, and never for a path
    // the API owns, so a mistyped endpoint still fails honestly.
    const wantsDocument = String(req.headers.accept ?? '').includes('text/html');
    const isApiPath = req.url.startsWith('/v1') || req.url.startsWith('/health');
    if (req.method === 'GET' && wantsDocument && !isApiPath && hasWebBundle()) {
      return sendWebBundle(reply);
    }
    return reply.status(404).send({
      error: { code: ERROR_CODES.NOT_FOUND, message: 'Route not found', requestId: req.id },
    } satisfies ApiErrorBody);
  });
}
